name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Build binary
        run: |
          mkdir -p dist
          BIN_NAME="migrate-v2-linux-${{ matrix.goarch }}"
          if [ "${{ matrix.goarch }}" = "arm64" ]; then
            echo "Building ARM64 binary using Docker"
            docker run --rm -v $PWD:/src -w /src --platform linux/arm64 golang:1.23 \
            bash -c "CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -ldflags '-s -w' -o dist/$BIN_NAME ."
          else
            echo "Building AMD64 binary natively"
            CGO_ENABLED=1 GOOS=linux GOARCH=amd64 \
            go build -ldflags "-s -w" -o dist/$BIN_NAME .
          fi

      - name: Package binary and generate SHA256
        run: |
          BIN_NAME="migrate-v2-linux-${{ matrix.goarch }}"
          TAR_NAME="${BIN_NAME}.tar.gz"
          tar -czf dist/$TAR_NAME -C dist $BIN_NAME
          sha256sum dist/$TAR_NAME > dist/${TAR_NAME}.sha256
          cat dist/${TAR_NAME}.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: migrate-v2-${{ matrix.goarch }}
          path: |
            dist/migrate-v2-linux-${{ matrix.goarch }}.tar.gz
            dist/migrate-v2-linux-${{ matrix.goarch }}.tar.gz.sha256

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Generate release notes with SHA256
        run: |
          echo "## Release Notes" > release-notes.md
          git log $(git describe --tags --abbrev=0 @^)..@ --pretty='* %s (%h)' >> release-notes.md
          echo "" >> release-notes.md
          echo "## SHA256 Checksums" >> release-notes.md
          for f in dist/*.sha256; do
            cat $f >> release-notes.md
          done
          cat release-notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.tar.gz
          body_path: release-notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}